apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: radio
  name: radio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radio
  template:
    metadata:
      labels:
        app: radio
    spec:
      containers:
        - image: 377225462902.dkr.ecr.us-east-1.amazonaws.com/learning-devops-sample-app:3cf4356
          name: sample-app-radio
          resources: {}
          env:
            - name: VAULT_ADDR
              value: 'http://vault.vault.svc.cluster.local:8200'
            - name: VAULT_PATH
              value: 'sample-app/env'
            - name: VAULT_USR
              valueFrom:
                secretKeyRef:
                  name: sample-app-env
                  key: VAULT_USR
            - name: VAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sample-app-env
                  key: VAULT_PASSWORD
      imagePullSecrets:
        - name: regcred
